### ISSUE TITLE
A way to destroy fragment

### ISSUE THREAD

**Issue by kellyselden** [lytics/ember-data.model-fragments#106]
use case:
```js
var person = store.getById('person', '1');

person.set('birthday', myNewBirthday);

var name = store.createFragment('name', {
  first : 'Hugor',
  last  : 'Hill'
});

person.set('name', name);

//then later on

var name = person.get('name');

person.set('name', null);

//what to do with name?
```
I don't want to rollback `person` and lose their birthday change. Should there be a `name.destroyFragment` or something similar to remove it from the store?

**Comment by slindberg** [comment]
What is it you'd like to do with the fragment? It should get GCed once the `name` var goes out of scope, since there's no identity map for fragments like there is for models.

**Comment by kellyselden** [comment]
I assumed it was cached in the store in some capacity. Is that not the case?

**Comment by slindberg** [comment]
Nope, model instances are the sole owners of fragments. Caching doesn't really make sense if you can't differentiate between two fragments with identical properties (i.e. no have unique IDs).

If you're finding that they aren't being cleaned up though, that's a bug. It's always possible I missed something (glaring or otherwise) that hangs onto references to fragments.

**Comment by kellyselden** [comment]
I will report back when I finish my implementation, but as it stands, there is no issue.
