### ISSUE TITLE
should consider using a null prototype object

### ISSUE THREAD

**Issue by stefanpenner** [lytics/ember-data.model-fragments#118]
here -> https://github.com/lytics/ember-data.model-fragments/blob/master/packages/model-fragments/lib/fragments/model.js#L107 and in similar situations, so that collisions with prototype members, or prototype members resulting from solution do not collide. Although `hasOwnProp` can help, the performance of it is sub-optimal.

**Comment by stefanpenner** [comment]
some of this may be fixed on [this long running branch](https://github.com/lytics/ember-data.model-fragments/pull/109) its worth applying any missing changes to that branch/pr

**Comment by slindberg** [comment]
I definitely see the advantage of using `Object.create(null)` in situations where the object will be each'ed over, or when you are using dynamic keys in general. But when keys are known in advance, e.g. [an options hash](https://github.com/lytics/ember-data.model-fragments/blob/v0.4.0/packages/model-fragments/lib/fragments/attributes.js#L65), it's hard to imagine a scenario where a single offending lib is the only point of failure due to a collision from a modified `Object.prototype`.

Are you of the opinion that every object literals should be replaced with `Object.create(null)`? If not, what is your internal decision making process?

**Comment by stefanpenner** [comment]
Only ones that have potential collisions, ones that have dynamic keys.

I believe that is similar to or comment
