### ISSUE TITLE
Default value for `hasManyFragments`

### ISSUE THREAD

**Issue by slindberg** [lytics/ember-data.model-fragments#40]
Currently when a `defaultValue` option isn't specified for a `hasManyFragments` attribute, [it is set to `null`](https://github.com/lytics/ember-data.model-fragments/blob/dade27ee147902794dc837058b6f608496fd30e4/packages/model-fragments/lib/fragments/attributes.js#L241). While `null` is a valid value of the property, it is more intuitive that the default is an empty fragment array, and is more consistent with how `DS.hasMany` works already. ~~In fact there currently is no way to force the creation of a fragment array once a record has been created.~~ However this is a minor breaking change, so should probably slated for a future major version bump.

Refs #36.

EDIT: a fragment array property can be set explicitly to an array-like object, which can either be empty or contain valid fragment models.

**Comment by louy** [comment]
I strongly agree with this. Any plans? It has been 5 months already.

**Comment by slindberg** [comment]
I don't currently have any plans to implement this (hence the 5 months you mention). Specifying a `defaultValue: []` option is a fairly low-friction solution that has worked well in practice, albeit slightly counterintuitive.

Since it is actually possible to set a fragment array property to an array after object creation, unlike my original comment asserted, this issue's urgency has dropped significantly. That said, PRs are always welcome.

**Comment by devinus** [comment]
This bit me today, I'd love for it to be the default.

**Comment by slindberg** [comment]
I'll make sure an empty array is the default value in 1.0

**Comment by christophersansone** [comment]
@slindberg I'm hoping to submit a PR in a bit.  Since this could be a breaking change for those relying on `defaultValue` to otherwise be undefined, how should we handle this?  We could introduce a deprecation warning for < 1.0 that requires a default value to be specified for `hasManyFragments`, and then safely change the default value for v1.0.  I imagine the default value is being specified the vast majority of the time, so this would just catch those edge cases and make sure they explicitly define it.  They can continue to use `null` or `undefined`, but it would have to be explicitly defined that way.

If we want to do that, I can submit PRs for both branches... which branches should I use?  Or we can just introduce the breaking change since it is not v1.0 yet.

**Comment by slindberg** [comment]
@christophersansone I added a warning that this will change in v1.0 in #126. The plan is to fix it on master before the 1.0 release. You're welcome to open a PR against master that I'll merge at the appropriate time (although it should be a one line fix, so don't feel obligated).

**Comment by christophersansone** [comment]
@slindberg Cool, yeah it's literally one line change with possibly a test to write.  Thought I'd pitch in to help get v1.0 out the door and just started at the top. :)

**Comment by slindberg** [comment]
@christophersansone Definitely appreciate the help!
