### ISSUE TITLE
Assign type key on createFragment of a polymorphic model

### ISSUE THREAD

**Issue by dukedave** [lytics/ember-data.model-fragments#59]
A few disclaimers:

1. I see in the readme that:
  > Model Fragments has support for reading polymorphic fragments

  I'll assume that creating a fragment doesn't fall within, 'reading'.

1. I see the `App.AnimalSerializer` example in the readme, this is related.

However :smile: ...

I just used `createFragment` to create a polymorphic model, let's say an `Elephant` in the readme example, but the `$type` property was not set.

I depend on the type key attribute else where in my app (via a `$type: DS.attr('string')` in the model), and worked around this by putting in the definition of `Elephant`:

```
  init: function() {
    this._super();
    this.set('$type', 'elephant');
```

So it works now, but I have a few questions:

1. Is this a bad idea?
1. If not, is it outside the scope of the project, or just not implemented yet?

**Comment by slindberg** [comment]
This behavior is in fact intentional, here's the rational: the `typeKey` attribute in the JSON gets encoded in the actual class that ends up getting instantiated, so keeping it as a property would be duplicating data that is already available and making two different ways to do the same thing (never a good idea). The other reason is that `ActiveModelAdapter`'s polymorphic support does not expose the type as a property either.

My advice is to import the fragment class and use the `instanceof` operator to check its type:

```javascript
import Elephant from '../models/elephant';

// Is this thing an elephant?
if (fragment instanceof Elephant) {
  // yep
}
```

However I realize that `Ember.MODEL_FACTORY_INJECTIONS = true;` makes this difficult (something I hope the Ember team will address), so if you have it on, you can fall back on `constructor.typeKey`:

```javascript
// Is this thing an elephant?
if (fragment.constructor.typeKey === 'elephant') {
  // yep
}
```

**Comment by dukedave** [comment]
Ah, thanks for clarifying @slindberg, that makes sense.
I'll call `$type: DS.attr('string')` an anti-pattern, and re-implement using `constructor.typeKey`.

And, for reference, looking up `constructor.typeKey` led me to emberjs/data#1642, where there's a similar discussion. Moreover they are using the type to pick a partial, which is exactly what I'm doing :smile:

**Comment by slindberg** [comment]
Sure thing. Creating a computed property is a good way to handle your scenario. I doubt if this will ever be added to `DS.Model`, simply because the Ember team is _very_ cautious about adding anything to the API, especially things that are trivial to do in an app.
