### ISSUE TITLE
hasMany access fragment by index in a template

### ISSUE THREAD

**Issue by tehmaestro** [lytics/ember-data.model-fragments#63]
Hi. How can I access an item from a hasMany relation, using the index, in a template.
 For example, I can use this with array in templates:
`array.[0].name`
 That doesn't work if array is a hasMany relation of the model, like:
`
model.array.[0].name`

**Comment by slindberg** [comment]
It looks like you are using features in handlebars 2.0.0, which I have no experience with (and which might not even have official support?). The fragment arrays returned by `DS.hasManyFragments` properties are just subclasses of `Ember.ArrayProxy`, so I'm guessing that the handlebars runtime that makes this work with plain arrays is naively using bracket syntax directly on the array proxy, which does not work.

```javascript
var arr = Ember.ArrayProxy.create({ content: [ 'foo', 'bar' ] });

arr[0]; // undefined
arr.objectAt(0); // 'foo'
arr.get('firstObject'); // 'foo'
```

If you are only concerned with the first or last elements of the array, you can always use the `firstObject`/`lastObject` properties in templates:

```handlebars
This is the first fragment's name: {{array.firstObject.name}}
This is the last fragment's name: {{array.lastObject.name}}
```

Closing, since this is more of an issue for the handlebars/htmlbars runtime in Ember proper.
