### ISSUE TITLE
Fragments RFC and model fragments

### ISSUE THREAD

**Issue by artzte** [lytics/ember-data.model-fragments#71]
Have you all seen the [RFC](https://github.com/ef4/rfcs/blob/element-and-fragment/active/0000-element-and-fragment.md) for fragments? Wondering if the authors are aware of this project and the potential confusion about names? I am increasingly feeling that model fragments is an indispensable / inseparable piece of the Ember Data ecosystem, for those of us consuming complex JSON documents with ID-less subcomponents. Has there been any discussion about pulling this functionality into core Ember Data? Honestly, I feel it is unlikely we would be using Ember Data at Avalara if not for this project.

**Comment by slindberg** [comment]
Yeah, the name is kind of unfortunate, but I'm super excited about that RFC. I suspect that the word 'fragment' was inspired by the native DOM fragment API. Or not – after all it's a fairly generic word. I've never been particularly fond of the word for this project anyway, it was just the best I could come up with.

As far as this becoming a part of ED core, I know there's interest but I don't know where that will lead. The TL;DR is, probably not anytime soon.

There are two scenarios that I could see coming to pass:

1. Support for sub-models is spiked in by a core ED contributor with way to much time on her/his hands. This infrastructure for this isn't ready: both relationship dirtying (see first bullet point [here](https://github.com/emberjs/data/issues/2545)) and a merge strategy (see [conflict resolution section in readme](https://github.com/lytics/ember-data.model-fragments#conflict-resolution)) must be addressed at a minimum.
2. ED starts to become more pluggable and exposes more of its state machine internals as public. This would probably result in an official sub-model plugin. Due to the ridiculous complexity inherent to model state/relationship management, I doubt this will ever be happen.

In either case, support for this project's API (and its implementation) will be abandoned. The most important thing to keep in mind is that there are only a handful of ED core contributors with very little bandwidth between them. So barring nested JSON sub-models becoming a high priority for one of their companies (read: someone's got to fund it), either option is a long ways away.

I'm gonna close this issue since it's not really actionable, but good to hear your feedback!

**Comment by artzte** [comment]
Yeah, for sure, and thanks for the feedback... perhaps this was not the best venue to raise those questions.
