### ISSUE TITLE
Fragment values reset on changes after first save

### ISSUE THREAD

**Issue by knownasilya** [lytics/ember-data.model-fragments#72]
Basically if you change a nested fragment's value, and then save the parent model it works. Now if you go and make another change, and save, it resets the value to the previous value upon save.

Here's an example setup:

```js
// model
export default DS.Model.extend({
  name: attr('string'),
  subdomain: attr('string'),
  settings: oneFragment('community-setting')
});

// community-setting fragment
export default DS.ModelFragment.extend({
  disclaimer: oneFragment('settings-disclaimer'),
  contact: oneFragment('settings-contact'),
  links: manyFragments('settings-link'),
  map: oneFragment('settings-map')
});

// settings-disclaimer fragment
export default DS.ModelFragment.extend({
  showOnFirstVisit: attr('boolean'),
  message: attr('string')
});
```

In the above code, if I modify `community.settings.disclaimer.message`, and `community.save()` it works fine. Now if I don't refresh the page, and change the value again, and hit save, the value is changed back to what it was last before this change.

So It's kind hard to create a jsbin with an ember-cli addon, so I hope this is enough.

**Comment by knownasilya** [comment]
@slindberg any ideas what this could be?

**Comment by chrisvariety** [comment]
We're using nested fragments in exactly this way and haven't run into this problem, so I think the issue may be in your code vs. ember data model fragments. I think a failing test would help diagnose, or a jsbin like thing. You can see https://github.com/ember-cli/ember-cli/issues/3050 for some ideas of how to create a jsbin with ember-cli addons.

**Comment by knownasilya** [comment]
http://ukkk41c97b7b.knownasilya.koding.io:3000/

So the issue is in the fact that I use something like:

```js
//my route
model() {
  return this.get('community.settings.disclaimer');
}
```

template
```hbs
{{input type='text' value=model.message}}
```

**Comment by slindberg** [comment]
Apologies, I've been on vacation for the last week.

@knownasilya I'm unable to create a failing test case for this, and unfortunately your koding link does not work for me. Can you reproduce this behavior outside of a route? In general I'd be wary of using a model fragment as the model for a route since they can get clobbered on saves, but since this is a `DS.hasOneFragment` property, you should be ok. Are you 100% certain that the response payload is correct for the second save?

I can't do much until I can repro it, hopefully you can work off of [this commit](https://github.com/lytics/ember-data.model-fragments/commit/4e8f4cbb8fc7d031ed132dc5f6be873c6c60e75e) to make a failing test.

**Comment by slindberg** [comment]
ping @knownasilya

**Comment by knownasilya** [comment]
@slindberg I'll try to get a failing test working this week.

**Comment by slindberg** [comment]
Thanks :+1:

**Comment by slindberg** [comment]
If you can provide a failing test case, jsbin, etc. please reopen.
