### ISSUE TITLE
"Attempting to register an unknown factory: `transform:fragment`" in serializer test

### ISSUE THREAD

**Issue by mbrakken** [lytics/ember-data.model-fragments#80]
I'm using ember-cli 0.2.3 and model-fragments 0.3.1. I have a serializer test for a model with fragments.

The test is currently just the default generated by ember-cli with added `needs`, namely
```javascript
import {
    moduleForModel,
    test
} from 'ember-qunit';

moduleForModel('invite-submission', {
    needs: [
        'serializer:invite-submission',
        'transform:fragment',
        'model:invite-review',
        'model:album-fragment',
        'model:artist-fragment'
    ]
});

// Replace this with your real tests.
test('it serializes records', function(assert) {
    var record = this.subject();

    var serializedRecord = record.serialize();

    assert.ok(serializedRecord);
});
```
If I include `'transform:fragment'` in my `needs` array as it is above, I get an error `Attempting to register an unknown factory: 'transform:fragment'`. If I leave out the transform declaration from the `needs` array, I get `Assertion Failed: Unable to find transform for 'fragment'`.

I'm not totally sure about the correct path forward other than stripping out the test. Nor do I know if this is an issue with model-fragments or a shortcoming of ember-cli's test suite, but I thought I'd start here. I appreciate any insight.

**Comment by slindberg** [comment]
This is happening because the transform is [registered directly in an initializer](https://github.com/lytics/ember-data.model-fragments/blob/v0.3.1/packages/model-fragments/lib/initializers.js#L9) which doesn't run for unit tests. Built-in ember data transforms are registered automatically by [ember-test-helpers](https://github.com/switchfly/ember-test-helpers/blob/v0.4.3/lib/ember-test-helpers/isolated-container.js#L72-L75)

AFAICT there's no way for addons to add to the isolated container, so for the time being you can register it manually using the `beforeEach` callback:

```javascript
import {
  moduleForModel,
  test
} from 'ember-qunit';

moduleForModel('foo', {
  needs: [ '...' ],
  beforeEach: function() {
    this.container.register('transform:fragment', DS.FragmentTransform);
  }
});

// ...
```

**Comment by igorT** [comment]
You can also in your app say:
`export default DS.FragmentTransform` in `app/transforms/fragments.js`
thnks to @rwjblue

**Comment by ldong** [comment]
Whoever comes later wondering how to test `serializer` that involves fragments in their models.

You may want to put this in your `serializer test`

```js
  needs: [
    'serializer:user',
    transform:fragment',
    'transform:fragment-array',
  ]
```
