### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by knownasilya** [lytics/ember-data.model-fragments#96]
Per the beta.18 release, `typeKey` should now be referenced as `modelName` and `snapshot.constructor` as `snapshot.type`

Currently it's still valid, but throws deprecation errors.

**Comment by jakesjews** [comment]
I'd be willing to make an attempt at fixing this. @slindberg do you want to try to do version detection for this one or just change the references?

**Comment by slindberg** [comment]
I believe the only offending line is [this one](https://github.com/lytics/ember-data.model-fragments/blob/v0.3.3/packages/model-fragments/lib/fragments/transform.js#L44), since all other references to `typeKey` are for polymorphism support.

I think the fix can be as simple as

```javascript
var modelName = snapshot.modelName || snapshot.typeKey;

return get(snapshot, 'record.store').serializerFor(modelName).serialize(snapshot);
```

@jakesjews if you want to open a PR, I'll give you a :raised_hands:

**Comment by jakesjews** [comment]
PR submitted. Your code suggestion did the trick.
